[package]
name = "competitive-rust-library"
version = "0.1.0"
authors = ["ktmtrtr <mtkt06311@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-snippet = "0.6.5"

[dev-dependencies]
